# Generated by Django 4.1.11 on 2023-09-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('sport', 'sport'), ('movie', 'movie'), ('celebrity', 'celebrity')], default='sport', max_length=20),
        ),
    ]
